{{- if and .Values.pgAdmin.enabled .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vnext.fullname" . }}-pgadmin-credentials
  labels:
    {{- include "vnext.labels" . | nindent 4 }}
    app: pgadmin4
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgAdmin.auth.email | default "admin@example.com" }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgAdmin.auth.password | default "password" }}
{{- end -}}