apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  features:
  - enabled: true
    name: HotReload
  metric:
    enabled: false
  metrics:
    enabled: true
  tracing:
    otel:
      endpointAddress: {{ include "vnext.otelEndpoint" . | quote }}
      isSecure: false
      protocol: http
    samplingRate: "1"