apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ include "vnext.fullname" . }}-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ include "vnext.redisEndpoint" . | quote }}
  - name: redisPassword
    secretKeyRef:
      name: workflow-secret
      key: redis-password
  - name: sentinelMasterName
    value: mymaster
  - name: sentinelPassword
    secretKeyRef:
      key: sentinel-password
      name: workflow-secret
  - name: failover
    value: true
auth:
  secretStore: {{ include "vnext.fullname" . }}-secret