apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ include "vnext.fullname" . }}-secret
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    {{- if .Values.global.externalVault.enabled }}
    - name: vaultAddr
      value: {{ .Values.global.externalVault.address }}
    - name: enginePath
      value: {{ .Values.global.externalVault.secretEngineName }}
    {{- else }}
    - name: vaultAddr
      value: http://{{ include "vnext.fullname" . }}-vault:8200
    - name: enginePath
      value: {{ printf "vnext-%s-engine" .Values.global.appDomain }}
    {{- end }}
    {{- if .Values.vault.enabled }}
    {{- if .Values.vault.server.dev.enabled }}
    - name: vaultToken
      value: "{{ .Values.vault.server.dev.devRootToken }}"
    {{- else }}
    - name: vaultToken
      value: "enter-vault-token"
    {{- end }}
    {{- else }}
    {{- if .Values.global.externalVault.enabled }}
    - name: vaultToken
      value: {{ .Values.global.externalVault.vaultToken | default "enter-vault-token" }}
    {{- else }}
    - name: vaultToken
      value: "enter-vault-token"
    {{- end }}
    {{- end }}
    - name: skipVerify
      value: true
    - name: vaultKVUsePrefix
      value: false
    - name: vaultKVPrefix
      value: workflow-secret
    - name: vaultValueType
      value: "map"