{{- if not .Values.auth.existingSecret -}}
{{- $secretName := include "redis-sentinel.fullname" . -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $redisPassword := "" -}}
{{- $sentinelPassword := "" -}}
{{- if $secret -}}
  {{- $redisPassword = index $secret.data "redis-password" | b64dec -}}
  {{- $sentinelPassword = index $secret.data "sentinel-password" | b64dec -}}
{{- else -}}
  {{- if .Values.redis.password -}}
    {{- $redisPassword = .Values.redis.password -}}
  {{- else -}}
    {{- $redisPassword = randAlphaNum 32 -}}
  {{- end -}}
  {{- if .Values.sentinel.password -}}
    {{- $sentinelPassword = .Values.sentinel.password -}}
  {{- else -}}
    {{- $sentinelPassword = randAlphaNum 32 -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-sentinel.fullname" . }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
  annotations:
    {{- if not (or .Values.redis.password .Values.sentinel.password) }}
    "helm.sh/resource-policy": keep
    {{- end }}
type: Opaque
data:
  redis-password: {{ $redisPassword | b64enc | quote }}
  sentinel-password: {{ $sentinelPassword | b64enc | quote }}
{{- end }}

