{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redis-sentinel.serviceAccountName" . }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
  annotations:
    # Create ServiceAccount before any other hooks (especially TLS cert job)
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

